# This is a basic workflow to help you get started with Actions

name: manual-inputs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
     empId:
      description: 'Enter Emp ID'
      required: true
      default: '0'
     empName:
      description: 'Enter Emp Name'
      required: true
      default: ''
env:
 My_NAME: Yousuf

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: my-build-job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TEST_VAR: 1234
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run validation
        if: github.event.inputs.empId == null || github.event.inputs.empId == 0 || github.event.inputs.empName == null || github.event.inputs.empName == ''
        run: echo "Invalid Inputs"; exit 1

      # Runs a set of commands using the runners shell
      - name: Print Id & Name
        run: echo ${{github.event.inputs.empId}} - ${{github.event.inputs.empName}} - ${{env.TEST_VAR}} - ${{env.My_NAME}}
