# This is a basic workflow to help you get started with Actions

name: matrix-workflow

on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: my-build-job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
     matrix:
      include:
       - empId: 1
         empName: Yousuf
       - empId: 2
         empName: Bilal
       - empId: 3
         empName: Faisal
     fail-fast: true
     max-parallel: 2

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello ${{ matrix.empId}} - ${{matrix.empName}}


